# numpy

In [4]:
import numpy as np
A = np.array([[56.0,0.0,4.4,68.0],
             [1.2,104.0,52.0,8.0],
             [1.8,135.0,99.0,0.9]])
print(A)

[[  56.     0.     4.4   68. ]
 [   1.2  104.    52.     8. ]
 [   1.8  135.    99.     0.9]]


In [21]:
print(A)
print(A.shape, A.ndim, A.size, A.dtype.name)

[[  56.     0.     4.4   68. ]
 [   1.2  104.    52.     8. ]
 [   1.8  135.    99.     0.9]]
(3, 4) 2 12 float64


In [10]:
cal = A.sum(axis=0)
print(cal)

[  59.   239.   155.4   76.9]


In [16]:
# 广播
print(cal.reshape(1,4))
print(1/cal.reshape(1,4))
print(A/cal.reshape(1,4))

[[  59.   239.   155.4   76.9]]
[[ 0.01694915  0.0041841   0.00643501  0.0130039 ]]
[[ 0.94915254  0.          0.02831403  0.88426528]
 [ 0.02033898  0.43514644  0.33462033  0.10403121]
 [ 0.03050847  0.56485356  0.63706564  0.01170351]]


In [22]:
b = np.array([6, 7, 8])
print(type(b))

<class 'numpy.ndarray'>


In [23]:
b = np.array([[6, 7, 8]])
print(type(b))

<class 'numpy.ndarray'>


In [24]:
np.zeros( (3,4) )

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [25]:
np.empty( (2,3) )  

array([[  2.17633953e-076,   4.16343114e+025,   9.96765994e+010],
       [  1.72371741e-047,   4.26725527e-287,   3.71061442e-316]])

In [26]:
 np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [27]:
np.arange( 0, 2, 0.3 ) 

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

In [29]:
from numpy import pi
np.linspace( 0, 2, 9 )    

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [30]:
x = np.linspace( 0, 2*pi, 100 )

In [31]:
f = np.sin(x)
f

array([  0.00000000e+00,   6.34239197e-02,   1.26592454e-01,
         1.89251244e-01,   2.51147987e-01,   3.12033446e-01,
         3.71662456e-01,   4.29794912e-01,   4.86196736e-01,
         5.40640817e-01,   5.92907929e-01,   6.42787610e-01,
         6.90079011e-01,   7.34591709e-01,   7.76146464e-01,
         8.14575952e-01,   8.49725430e-01,   8.81453363e-01,
         9.09631995e-01,   9.34147860e-01,   9.54902241e-01,
         9.71811568e-01,   9.84807753e-01,   9.93838464e-01,
         9.98867339e-01,   9.99874128e-01,   9.96854776e-01,
         9.89821442e-01,   9.78802446e-01,   9.63842159e-01,
         9.45000819e-01,   9.22354294e-01,   8.95993774e-01,
         8.66025404e-01,   8.32569855e-01,   7.95761841e-01,
         7.55749574e-01,   7.12694171e-01,   6.66769001e-01,
         6.18158986e-01,   5.67059864e-01,   5.13677392e-01,
         4.58226522e-01,   4.00930535e-01,   3.42020143e-01,
         2.81732557e-01,   2.20310533e-01,   1.58001396e-01,
         9.50560433e-02,

# pandas

In [5]:
import pandas as pd
import numpy as np
s = pd.Series([1,3,5,np.nan,6,8])
print(type(s),s)

<class 'pandas.core.series.Series'> 0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64


In [8]:
dates = pd.date_range('20130101', periods=6)
print(type(dates))
print(dates)

<class 'pandas.core.indexes.datetimes.DatetimeIndex'>
DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')


In [10]:
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))
print(df)

                   A         B         C         D
2013-01-01  1.850287 -0.234966  0.199195 -1.771369
2013-01-02  0.287611  0.502898  0.621793 -0.185249
2013-01-03 -0.734727  0.628346  0.306437 -1.121796
2013-01-04  1.501572 -1.430041 -1.150788 -0.006700
2013-01-05  0.084963  0.114777  0.618499 -0.440819
2013-01-06  0.614123  0.239053 -1.316439 -0.617104


In [14]:
# 必须有c，不然要index
df2 = pd.DataFrame({
    'a':1,
    'b':'foo',
    'c':pd.Series(1,index=list(range(4)),dtype='float32'),
})
print(df2)

   a    b    c
0  1  foo  1.0
1  1  foo  1.0
2  1  foo  1.0
3  1  foo  1.0


In [18]:
df.head(2)

A         B         C         D
2013-01-01  1.850287 -0.234966  0.199195 -1.771369
2013-01-02  0.287611  0.502898  0.621793 -0.185249

In [19]:
df.tail(2)

A         B         C         D
2013-01-05  0.084963  0.114777  0.618499 -0.440819
2013-01-06  0.614123  0.239053 -1.316439 -0.617104

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 6 entries, 2013-01-01 to 2013-01-06
Freq: D
Data columns (total 4 columns):
A    6 non-null float64
B    6 non-null float64
C    6 non-null float64
D    6 non-null float64
dtypes: float64(4)
memory usage: 368.0 bytes


In [22]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [23]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [24]:
df.values

array([[ 1.85028676, -0.23496632,  0.19919487, -1.77136929],
       [ 0.28761137,  0.50289835,  0.62179341, -0.18524895],
       [-0.73472667,  0.62834647,  0.30643699, -1.12179646],
       [ 1.50157156, -1.43004052, -1.1507877 , -0.0066996 ],
       [ 0.08496271,  0.11477697,  0.61849877, -0.44081854],
       [ 0.61412307,  0.23905325, -1.31643921, -0.61710442]])

In [25]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.600638 -0.029989 -0.120217 -0.690506
std    0.950851  0.750050  0.880155  0.654963
min   -0.734727 -1.430041 -1.316439 -1.771369
25%    0.135625 -0.147530 -0.813292 -0.995623
50%    0.450867  0.176915  0.252816 -0.528961
75%    1.279709  0.436937  0.540483 -0.249141
max    1.850287  0.628346  0.621793 -0.006700

In [26]:
df.T

2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A    1.850287    0.287611   -0.734727    1.501572    0.084963    0.614123
B   -0.234966    0.502898    0.628346   -1.430041    0.114777    0.239053
C    0.199195    0.621793    0.306437   -1.150788    0.618499   -1.316439
D   -1.771369   -0.185249   -1.121796   -0.006700   -0.440819   -0.617104

In [29]:
df.sort_index(axis=1, ascending=True)

A         B         C         D
2013-01-01  1.850287 -0.234966  0.199195 -1.771369
2013-01-02  0.287611  0.502898  0.621793 -0.185249
2013-01-03 -0.734727  0.628346  0.306437 -1.121796
2013-01-04  1.501572 -1.430041 -1.150788 -0.006700
2013-01-05  0.084963  0.114777  0.618499 -0.440819
2013-01-06  0.614123  0.239053 -1.316439 -0.617104

In [32]:
df.sort_index(axis=0, ascending=True)

A         B         C         D
2013-01-01  1.850287 -0.234966  0.199195 -1.771369
2013-01-02  0.287611  0.502898  0.621793 -0.185249
2013-01-03 -0.734727  0.628346  0.306437 -1.121796
2013-01-04  1.501572 -1.430041 -1.150788 -0.006700
2013-01-05  0.084963  0.114777  0.618499 -0.440819
2013-01-06  0.614123  0.239053 -1.316439 -0.617104

In [35]:
df.sort_values(by='B', ascending=False)

A         B         C         D
2013-01-03 -0.734727  0.628346  0.306437 -1.121796
2013-01-02  0.287611  0.502898  0.621793 -0.185249
2013-01-06  0.614123  0.239053 -1.316439 -0.617104
2013-01-05  0.084963  0.114777  0.618499 -0.440819
2013-01-01  1.850287 -0.234966  0.199195 -1.771369
2013-01-04  1.501572 -1.430041 -1.150788 -0.006700

In [36]:
df['A']

2013-01-01    1.850287
2013-01-02    0.287611
2013-01-03   -0.734727
2013-01-04    1.501572
2013-01-05    0.084963
2013-01-06    0.614123
Freq: D, Name: A, dtype: float64

In [37]:
df[0:3]

A         B         C         D
2013-01-01  1.850287 -0.234966  0.199195 -1.771369
2013-01-02  0.287611  0.502898  0.621793 -0.185249
2013-01-03 -0.734727  0.628346  0.306437 -1.121796

In [38]:
df['20130102':'20130104']

A         B         C         D
2013-01-02  0.287611  0.502898  0.621793 -0.185249
2013-01-03 -0.734727  0.628346  0.306437 -1.121796
2013-01-04  1.501572 -1.430041 -1.150788 -0.006700

In [39]:
dates[0]

Timestamp('2013-01-01 00:00:00', freq='D')

In [43]:
 df.loc[dates[0]]

A    1.850287
B   -0.234966
C    0.199195
D   -1.771369
Name: 2013-01-01 00:00:00, dtype: float64

In [44]:
df.loc['20130101']

A    1.850287
B   -0.234966
C    0.199195
D   -1.771369
Name: 2013-01-01 00:00:00, dtype: float64

In [47]:
df.loc[:,['A','B']]

A         B
2013-01-01  1.850287 -0.234966
2013-01-02  0.287611  0.502898
2013-01-03 -0.734727  0.628346
2013-01-04  1.501572 -1.430041
2013-01-05  0.084963  0.114777
2013-01-06  0.614123  0.239053

In [48]:
df.loc['20130102':'20130104',['A','B']]

A         B
2013-01-02  0.287611  0.502898
2013-01-03 -0.734727  0.628346
2013-01-04  1.501572 -1.430041

In [49]:
df.loc[dates[0],'A']

1.8502867610086222

In [54]:
df.loc['20130101','A']

1.8502867610086222

In [55]:
df.iloc[0]

A    1.850287
B   -0.234966
C    0.199195
D   -1.771369
Name: 2013-01-01 00:00:00, dtype: float64

In [56]:
df.iloc[0,0]

1.8502867610086222

In [57]:
df.iat[0,0]

1.8502867610086222

In [60]:
df[df.A>0]

A         B         C         D
2013-01-01  1.850287 -0.234966  0.199195 -1.771369
2013-01-02  0.287611  0.502898  0.621793 -0.185249
2013-01-04  1.501572 -1.430041 -1.150788 -0.006700
2013-01-05  0.084963  0.114777  0.618499 -0.440819
2013-01-06  0.614123  0.239053 -1.316439 -0.617104

In [61]:
df[df>0]

A         B         C   D
2013-01-01  1.850287       NaN  0.199195 NaN
2013-01-02  0.287611  0.502898  0.621793 NaN
2013-01-03       NaN  0.628346  0.306437 NaN
2013-01-04  1.501572       NaN       NaN NaN
2013-01-05  0.084963  0.114777  0.618499 NaN
2013-01-06  0.614123  0.239053       NaN NaN

In [62]:
pd

<module 'pandas' from 'c:\\python36\\lib\\site-packages\\pandas\\__init__.py'>

In [63]:
df

A         B         C         D
2013-01-01  1.850287 -0.234966  0.199195 -1.771369
2013-01-02  0.287611  0.502898  0.621793 -0.185249
2013-01-03 -0.734727  0.628346  0.306437 -1.121796
2013-01-04  1.501572 -1.430041 -1.150788 -0.006700
2013-01-05  0.084963  0.114777  0.618499 -0.440819
2013-01-06  0.614123  0.239053 -1.316439 -0.617104

In [64]:
df.to_csv('aa.csv')

In [65]:
df.to_excel('aa.xlsx', sheet_name='Sheet2')

ModuleNotFoundError: No module named 'openpyxl'